# Generated by Django 3.2.16 on 2026-04-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_auto_20260407_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
