# Generated by Django 3.2.16 on 2026-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('при получении', 'При получении'), ('онлайн', 'Онлайн')], default='', max_length=20),
        ),
    ]
