# Generated by Django 3.2.16 on 2026-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, choices=[('Moscow', 'Москва'), ('Saint Petersburg', 'Санкт-Петербург'), ('Kazan', 'Казань'), ('Tomsk', 'Томск'), ('Novosibirsk', 'Новосибирск'), ('Ekaterinburg', 'Екатеринбург')], max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='post_office',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
