# Generated by Django 3.2.16 on 2026-04-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20260407_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post_office',
        ),
    ]
